version: "3.8"
services:

  # PHP Service
  php:
    container_name: php
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:80
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - laravel

  # Database Server
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - 3305:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="no"
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp
      - MYSQL_ROOT_PASSWORD=webapp
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - laravel

volumes:
  db-data: ~

networks:
  laravel:
    driver: bridge
